import { useState } from 'react'
import { useQuery, useQueryClient } from 'react-query'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Loader from '../components/Loader'

const fetchFilteredCountries = async ({ queryKey }) => {
  const [_key, { country }] = queryKey

  if (country) {
    const res = await fetch(`https://restcountries.com/v3.1/all`)
    const data = await res.json()

    return data.filter((c) =>
      c.name.common.toLowerCase().includes(`${country}`),
    )
  }

  const res = await fetch(`https://restcountries.com/v3.1/all`)
  return res.json()
}

export default function Home({ countries }) {
  // const queryClient = useQueryClient()

  const [country, setCountry] = useState('')

  const { data, status, isFetching } = useQuery(
    ['countries', { country }],
    fetchFilteredCountries,
    {
      initialData: countries,
    },
  )

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input
          type="text"
          name="country"
          onChange={(e) => setCountry(e.target.value)}
        />
      </div>
      <div className={styles.grid}>
        {(isFetching || status === 'loading') && <Loader />}
        {status === 'success' &&
          !isFetching &&
          data.map((item, index) => (
            <Link
              key={index}
              href={`/${encodeURIComponent(item.name.common.toLowerCase())}`}
            >
              <div className={styles.card}>
                <div className={styles.img__wrapper}>
                  <Image src={item.flags.svg} layout="fill" objectFit="cover" />
                </div>
                <div className={styles.content}>
                  <h4>{item.name.common}</h4>
                  <ul>
                    <li>
                      <strong>Population:</strong>
                      {item.population.toLocaleString()}
                    </li>
                    <li>
                      <strong>Region:</strong>
                      {item.region}
                    </li>
                    <li>
                      <strong>Capital:</strong>
                      {item.capital}
                    </li>
                  </ul>
                </div>
              </div>
            </Link>
          ))}
      </div>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch(`https://restcountries.com/v3.1/all`)
  const data = await res.json()

  return { props: { countries: data } }
}
